### ISSUE TITLE
Update to TLP tags

### ISSUE THREAD

**Issue by HBadger0017** [SigmaHQ/sigma-specification#104]
Is there a mechanism to update the TLP tags to include the current First.org listings?  Specifically, I use TLP:AMBER+STRICT often and would like to use it in my sigma rules.

I am comfortable updating it myself but haven't found where the tag references are located.  (Truth in lending, I am using VSCode for my rule development so this may not be the right place).

Thanks in advance.

**Comment by nasbench** [comment]
Hey and thanks for opening this issue.

The tag definition is described here https://github.com/SigmaHQ/sigma-specification/blob/main/Tags_specification.md while the text allows the use of any tags defined in https://www.first.org/tlp/ it could use some clarification for cases of combined TLP values.

I suggest to use a notation of underscores example `tlp.amber_strict` instead of the `+` to make it consistent with the other tags.

You can submit a PR and we'll review as soon as we can :)

**Comment by nasbench** [comment]
Will be resolved in https://github.com/humpalum/vscode-sigma/pull/24

This would allow for the writing of `amber+strict` in a sigma rule tags section in the format `tlp.amber-strict`
